import Foundation

/// Spectra's own configuration model, stored as TOML at ~/.config/spectra/config.toml.
/// Values are translated to ghostty config format when loading libghostty.
struct SpectraConfig {
    var font = FontConfig()
    var appearance = AppearanceConfig()
    var cursor = CursorConfig()
    var general = GeneralConfig()

    struct FontConfig {
        var family: String = ""
        var size: Double = 13
        var lineHeight: Double = 1.0
    }

    struct AppearanceConfig {
        var theme: String = ""
        var backgroundOpacity: Double = 1.0
        var windowPaddingX: Int = 0
        var windowPaddingY: Int = 0
    }

    struct CursorConfig {
        var style: String = "block"
        var blink: Bool = true
    }

    struct GeneralConfig {
        var shell: String = ""
        var workingDirectory: String = ""
        var confirmClose: Bool = true
        var scrollbackLines: Int = 10000
    }

    // MARK: - File path

    static var configDir: URL {
        FileManager.default.homeDirectoryForCurrentUser
            .appendingPathComponent(".config/spectra", isDirectory: true)
    }

    static var configFile: URL {
        configDir.appendingPathComponent("config.toml")
    }

    // MARK: - Load from TOML

    static func load() -> SpectraConfig {
        var config = SpectraConfig()
        guard let content = try? String(contentsOf: configFile, encoding: .utf8) else {
            return config
        }

        let parsed = TOMLParser.parse(content)

        // [font]
        if let v = parsed["font.family"] { config.font.family = v }
        if let v = parsed["font.size"], let d = Double(v) { config.font.size = d }
        if let v = parsed["font.line-height"], let d = Double(v) { config.font.lineHeight = d }

        // [appearance]
        if let v = parsed["appearance.theme"] { config.appearance.theme = v }
        if let v = parsed["appearance.background-opacity"], let d = Double(v) {
            config.appearance.backgroundOpacity = d
        }
        if let v = parsed["appearance.window-padding-x"], let i = Int(v) {
            config.appearance.windowPaddingX = i
        }
        if let v = parsed["appearance.window-padding-y"], let i = Int(v) {
            config.appearance.windowPaddingY = i
        }

        // [cursor]
        if let v = parsed["cursor.style"] { config.cursor.style = v }
        if let v = parsed["cursor.blink"] { config.cursor.blink = (v == "true") }

        // [general]
        if let v = parsed["general.shell"] { config.general.shell = v }
        if let v = parsed["general.working-directory"] { config.general.workingDirectory = v }
        if let v = parsed["general.confirm-close"] { config.general.confirmClose = (v == "true") }
        if let v = parsed["general.scrollback-lines"], let i = Int(v) {
            config.general.scrollbackLines = i
        }

        return config
    }

    // MARK: - Save to TOML

    func save() throws {
        let dir = Self.configDir
        try FileManager.default.createDirectory(at: dir, withIntermediateDirectories: true)

        var lines: [String] = []
        lines.append("# Spectra Terminal Configuration")
        lines.append("")

        lines.append("[font]")
        if !font.family.isEmpty { lines.append("family = \"\(font.family)\"") }
        lines.append("size = \(formatNumber(font.size))")
        lines.append("line-height = \(formatNumber(font.lineHeight))")
        lines.append("")

        lines.append("[appearance]")
        if !appearance.theme.isEmpty { lines.append("theme = \"\(appearance.theme)\"") }
        lines.append("background-opacity = \(formatNumber(appearance.backgroundOpacity))")
        lines.append("window-padding-x = \(appearance.windowPaddingX)")
        lines.append("window-padding-y = \(appearance.windowPaddingY)")
        lines.append("")

        lines.append("[cursor]")
        lines.append("style = \"\(cursor.style)\"")
        lines.append("blink = \(cursor.blink)")
        lines.append("")

        lines.append("[general]")
        if !general.shell.isEmpty { lines.append("shell = \"\(general.shell)\"") }
        if !general.workingDirectory.isEmpty {
            lines.append("working-directory = \"\(general.workingDirectory)\"")
        }
        lines.append("confirm-close = \(general.confirmClose)")
        lines.append("scrollback-lines = \(general.scrollbackLines)")
        lines.append("")

        try lines.joined(separator: "\n").write(to: Self.configFile, atomically: true, encoding: .utf8)
    }

    // MARK: - Translate to ghostty config format

    func toGhosttyConfig() -> String {
        var lines: [String] = []
        lines.append("# Auto-generated by Spectra — do not edit")

        if !font.family.isEmpty { lines.append("font-family = \(escapeGhosttyValue(font.family))") }
        lines.append("font-size = \(formatNumber(font.size))")
        if font.lineHeight != 1.0 {
            // ghostty uses percentage adjustment: 1.2 line-height = 20% increase
            let pct = Int((font.lineHeight - 1.0) * 100)
            if pct != 0 { lines.append("adjust-cell-height = \(pct)%") }
        }

        if !appearance.theme.isEmpty { lines.append("theme = \(escapeGhosttyValue(appearance.theme))") }
        lines.append("background-opacity = \(formatNumber(appearance.backgroundOpacity))")
        lines.append("window-padding-x = \(appearance.windowPaddingX)")
        lines.append("window-padding-y = \(appearance.windowPaddingY)")

        lines.append("cursor-style = \(cursor.style)")
        lines.append("cursor-style-blink = \(cursor.blink)")

        if !general.shell.isEmpty { lines.append("command = \(escapeGhosttyValue(general.shell))") }
        lines.append("scrollback-limit = \(general.scrollbackLines)")

        return lines.joined(separator: "\n") + "\n"
    }

    private func escapeGhosttyValue(_ value: String) -> String {
        value.replacingOccurrences(of: "\n", with: "")
             .replacingOccurrences(of: "\r", with: "")
    }

    private func formatNumber(_ value: Double) -> String {
        value == value.rounded() ? String(Int(value)) : String(value)
    }
}

// MARK: - Minimal TOML Parser

enum TOMLParser {
    /// Parse TOML content into a flat dictionary keyed by "section.key".
    static func parse(_ content: String) -> [String: String] {
        var result: [String: String] = [:]
        var currentSection = ""

        for line in content.components(separatedBy: .newlines) {
            let trimmed = line.trimmingCharacters(in: .whitespaces)

            // Skip empty lines and comments
            if trimmed.isEmpty || trimmed.hasPrefix("#") { continue }

            // Section header
            if trimmed.hasPrefix("[") && trimmed.hasSuffix("]") {
                currentSection = String(trimmed.dropFirst().dropLast())
                    .trimmingCharacters(in: .whitespaces)
                continue
            }

            // Key = Value
            guard let eqIdx = trimmed.firstIndex(of: "=") else { continue }
            let key = trimmed[trimmed.startIndex..<eqIdx]
                .trimmingCharacters(in: .whitespaces)
            var value = trimmed[trimmed.index(after: eqIdx)...]
                .trimmingCharacters(in: .whitespaces)

            // Strip quotes from string values, or strip inline comments for unquoted values
            if value.hasPrefix("\"") && value.hasSuffix("\"") && value.count >= 2 {
                value = String(value.dropFirst().dropLast())
            } else if let hashIdx = value.firstIndex(of: "#") {
                // Strip inline comment for unquoted values: `size = 13 # my size`
                value = value[value.startIndex..<hashIdx]
                    .trimmingCharacters(in: .whitespaces)
            }

            let fullKey = currentSection.isEmpty ? key : "\(currentSection).\(key)"
            result[fullKey] = value
        }

        return result
    }
}
